name: CI for Selenium Cucumber JUnit Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Download and set up Maven
      run: |
        curl -sL https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip -o maven.zip
        Expand-Archive -Path maven.zip -DestinationPath $env:USERPROFILE
        echo "MAVEN_HOME=$env:USERPROFILE/apache-maven-3.8.4" >> $env:GITHUB_ENV
        echo "PATH=$env:MAVEN_HOME/bin;$env:PATH" >> $env:GITHUB_ENV

    - name: Set up Maven settings
      run: |
        $env:M2_HOME = "$env:USERPROFILE/apache-maven-3.8.4"
        $env:PATH = "$env:M2_HOME/bin;$env:PATH"
        maven --version

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run tests
      run: mvn test
